### PR TITLE
truncate text preview in list to 50 words

### PR DESCRIPTION
**Pull request by petrjasek**

### CODE REVIEW

**Comment by aleksandarjelicic** [comment]
@petrjasek why only 50? You added it as an example for truncate functionality?
In design it has at least 3 lines of text. It should be 350 or 450.

**Comment by petrjasek** [comment]
because in the spec it's 40 but that seemed too short https://dev.sourcefabric.org/browse/SDAN-41

**Comment by petrjasek** [comment]
reading it again - my bad, should be 50 words not characters :wink:

**Comment by aleksandarjelicic** [comment]
np, it's fine now.

**Pull request merged**
