### PR TITLE
Displaying the notification list from the top menu notification icon

### PR DESCRIPTION
**Pull request by akintolga**
- Styles on the pop-over are temporary until the design is ready

### CODE REVIEW

**Comment by petrjasek** [comment]
not sure if we should display notification about new items in the current list on top, afaik there should be refresh button with a number above current list.
also it doesn't work as notifications, because now if you don't open the notifications list while there are new items and you reload the page I guess it gets lost, while notifications should stay until you clear it.

**Comment by petrjasek** [comment]
and ideally would put this notifications list into its own app, shouldn't be part of wire

**Comment by akintolga** [comment]
I see your points. Probably we need more clarification about this section:
https://wiki.sourcefabric.org/display/AAPNEWS/UI+Design?preview=/65044524/77824051/AAP_Newsroom_Newswire_Notifications_2.png

**Comment by akintolga** [comment]
Closing as I'm creating a new one to cover the notifications

**Pull request closed without merging**
